version: "3.7"

services:
  file_server:
    build: .
    ports:
      - "5150:5150"
    networks:
      - dbs_network
    volumes:
      - ./root:/app/root
      - ./public:/app/public
    restart: always

networks:
  dbs_network:
    name: startdbs_default
    external: true